# Tensor 이해하기

Scalar : 0 차원, 1  
Vector : 1 차원, [1, 2]  
Matrix : 2 차원, [1, 2   3, 4]  
tensow : [[1, 2], [3, 4]]

In [3]:
import numpy as np

## 0차원
> numpy array는 1 또는 5, 10와 같은 숫자 데이터를 array화 할수 있다.

In [4]:
arr = np.array(5)

In [5]:
arr.shape

()

In [6]:
arr.ndim

0

## 1차원

In [7]:
arr = np.array([5])
arr

array([5])

In [8]:
arr.shape

(1,)

[]에 따라서 차원이 갈린다.

In [9]:
arr = np.array([5, 3, 1])
arr

array([5, 3, 1])

In [10]:
arr.shape

(3,)

In [11]:
# 1차원의 표현은 (3) -> (3, ) 이다.

## 2차원

In [13]:
arr = np.array([[1, 2, 3]])
arr.shape

(1, 3)

In [14]:
arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr.shape

(3, 3)

In [15]:
arr = np.array([[10]])
arr.shape

(1, 1)

In [17]:
arr.ndim

2

## 다차원

In [20]:
arr = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]], ])
arr

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [21]:
arr.shape

(3, 3, 3)

In [22]:
arr = np.array([[[1], [2], [3]]])
arr

array([[[1],
        [2],
        [3]]])

In [23]:
arr.shape

(1, 3, 1)

shape을 계속 보다보면 데이터의 구조를 파악할 수 있게 된다.