# 학습 목표
* TensorFlow 2.0 간단한 사용법

In [1]:
import numpy as np
import tensorflow as tf

# Tensor 생성


### List 생성

In [2]:
[1, 2, 3]

[1, 2, 3]

In [3]:
[[1, 2, 3], [1, 2, 3]]

[[1, 2, 3], [1, 2, 3]]

### Array 생성

In [4]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

In [6]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.shape

(2, 3)

### Tensor 생성

* tf.constant()
 * list => Tensor
 
np array와 같이 동작을 한다.

In [8]:
tf.constant([1, 2, 3])

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

* tf.constant()
 * tuple => Tensor

In [11]:
tf.constant(((1, 2, 3), (1, 2, 3)))

<tf.Tensor: id=1, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

* tf.constant()
 * array => Tensor

In [13]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [14]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

###  Tensor에 담긴 정보 확인
 
* shape확인

In [16]:
tensor.shape

TensorShape([3])

* data type 확인
    * Data Type에 따라서 모델의 무게나 성능 차이에도 영향을 줄 수 있다.

In [17]:
tensor.dtype

tf.int32

* data type 정의

In [19]:
# tf.constant([1, 2, 3], dtype=tf.uint8)
tensor = tf.constant([1, 2, 3], dtype=tf.float32)

<tf.Tensor: id=4, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

* date type 변환
    * Numpy에서 astype()으로 설정하듯이, Tensorflow에서 tf.cast로 사용

In [22]:
arr = np.array([1, 2, 3], dtype=np.float32)

In [24]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
tensor

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [26]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: id=5, shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

* Tensor에서 Numpy로 불러오기
    * .numpy()

In [27]:
tensor.numpy()

array([1, 2, 3])

In [28]:
np.array(tensor)

array([1, 2, 3])

type()을 사용하여 Numpy array로 변환된것 확인

In [29]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [30]:
type(tensor.numpy())

numpy.ndarray

## 난수 생성

* Normal Distribution은 중심 극한 이론에 의한 연속적인 모양
* Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분포

* numpy에서는 normal distrubution을 기본적으로 생성
    * np.random.randn()

In [31]:
np.random.randn(9)

array([ 0.99152341,  0.30712726, -1.3506425 ,  0.51208265,  0.02964786,
        1.07076647, -0.93692122, -0.16067883,  0.14550825])

* tf.random.normal
    * Tensorflow에서 Normal Distribution

In [33]:
tf.random.normal([3, 3])

<tf.Tensor: id=14, shape=(3, 3), dtype=float32, numpy=
array([[-1.6714245 ,  3.1482756 , -0.07095209],
       [-0.88998914,  0.83848244, -1.1811081 ],
       [ 0.3512603 , -0.33218277,  1.2372893 ]], dtype=float32)>

* tf.random.uniform
    * Tensorflow에서 Uniform Distribution

In [35]:
tf.random.uniform([4, 4])

<tf.Tensor: id=21, shape=(4, 4), dtype=float32, numpy=
array([[0.76389325, 0.7348106 , 0.97999024, 0.7055365 ],
       [0.00512648, 0.95551217, 0.251109  , 0.15258968],
       [0.71915054, 0.8820076 , 0.7121477 , 0.57558763],
       [0.4443822 , 0.34889543, 0.28563535, 0.6947633 ]], dtype=float32)>